-- MySQL Script generated by MySQL Workbench
-- 06/09/17 11:21:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema triangle
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema triangle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `triangle` DEFAULT CHARACTER SET utf8 ;
USE `triangle` ;

-- -----------------------------------------------------
-- Table `triangle`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `triangle`.`users` ;

CREATE TABLE IF NOT EXISTS `triangle`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `triangle`.`chat_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `triangle`.`chat_messages` ;

CREATE TABLE IF NOT EXISTS `triangle`.`chat_messages` (
  `id` BIGINT(14) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT NOW(),
  `user_id` INT(11) UNSIGNED NOT NULL,
  `streamer_id` INT(11) UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_messages_users_idx` (`user_id` ASC),
  INDEX `fk_chat_messages_users1_idx` (`streamer_id` ASC),
  CONSTRAINT `fk_chat_messages_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `triangle`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_messages_users1`
    FOREIGN KEY (`streamer_id`)
    REFERENCES `triangle`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `triangle`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `triangle`;
INSERT INTO `triangle`.`users` (`id`, `username`, `password`, `firstname`, `lastname`) VALUES (1, 'HugoZink', '$2a$04$CqYnEGzH8Uxpdm.Djssu8eeJlAM0P32IWbfebhYHGw5yzjXThT7ty', 'Hugo', 'Zink');
INSERT INTO `triangle`.`users` (`id`, `username`, `password`, `firstname`, `lastname`) VALUES (2, 'RichardBos', '$2a$04$Y7oh6/pSdBG3pL6pg44r5uXTjVe/Jc0KDSvsVyz0cuf9.I6uiBlwG', 'Richard', 'Bos');
INSERT INTO `triangle`.`users` (`id`, `username`, `password`, `firstname`, `lastname`) VALUES (3, 'DannyTam', '$2a$04$AQbcszMLP2Sk1gdytdfTke7MsOUQTc9onzJRvUqVS8/s83NJqf5da', 'Danny', 'Tam');

COMMIT;

